// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Decodes the first barcode found in `pixels`.
///
/// pixels           borrowed, never freed by this fn.
/// byte_length      total readable bytes at `pixels` (bounds-checked against
/// width/height/row_stride before any pixel is touched).
/// row_stride_bytes bytes per row. 0 means "tightly packed"
/// (width * bytes_per_pixel). Must otherwise be >=
/// width * bytes_per_pixel. This is how camera Y-planes with
/// padded rows are consumed zero-copy.
/// pixel_format     one of ZXD_PIXEL_*.
/// formats_mask     ZXD_FORMAT_* bits; 0 = all formats.
/// try_harder       nonzero enables tryHarder/tryRotate/tryInvert. Slower;
/// intended for single still images, not camera streams.
/// out              caller-allocated; zeroed by this fn on entry. On ZXD_OK
/// the caller owns the members and must call
/// zxd_read_result_release (or free members from Dart).
/// On any other status there is nothing to free.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Pointer<zxd_read_result>,
  )
>()
external int zxd_read(
  ffi.Pointer<ffi.Uint8> pixels,
  int byte_length,
  int width,
  int height,
  int row_stride_bytes,
  int pixel_format,
  int formats_mask,
  int try_harder,
  ffi.Pointer<zxd_read_result> out,
);

/// Frees the members of `result` (NOT `result` itself) and zeroes the struct.
/// Safe to call multiple times, and safe on a zeroed struct.
@ffi.Native<ffi.Void Function(ffi.Pointer<zxd_read_result>)>()
external void zxd_read_result_release(ffi.Pointer<zxd_read_result> result);

/// Encodes `payload` as an Aztec symbol.
///
/// payload      borrowed. Restricted to printable ASCII (0x20..0x7E). This is
/// a deliberate envelope contract, not a zxing limitation: the
/// pairing payload is `<prefix>:<base64url>` so that every
/// decoder in the fallback chain (Apple Vision, ML Kit, zxing)
/// round-trips it byte-exactly.
/// error_correction_percent  0..99, mapped by zxing-cpp/zint to the closest
/// supported Aztec level (10/23/36/50), or -1 for its default.
/// out          caller-allocated; zeroed on entry. On ZXD_OK caller owns
/// `bits` and must call zxd_matrix_release (or free from Dart).
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
    ffi.Int32,
    ffi.Pointer<zxd_matrix>,
  )
>()
external int zxd_encode_aztec(
  ffi.Pointer<ffi.Uint8> payload,
  int payload_length,
  int error_correction_percent,
  ffi.Pointer<zxd_matrix> out,
);

/// Frees `matrix->bits` (NOT `matrix` itself) and zeroes the struct. Safe to
/// call multiple times, and safe on a zeroed struct.
@ffi.Native<ffi.Void Function(ffi.Pointer<zxd_matrix>)>()
external void zxd_matrix_release(ffi.Pointer<zxd_matrix> matrix);

/// Returns ZXD_ABI_VERSION of the loaded binary. Dart checks this before any
/// other call and refuses to run on mismatch.
@ffi.Native<ffi.Int32 Function()>()
external int zxd_abi_version();

/// Returns a process-lifetime, NUL-terminated ASCII build description owned by
/// the library. The caller must not free it.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> zxd_build_info();

/// ---------------------------------------------------------------------------
/// zxd_read: decode one barcode from a pixel buffer.
/// ---------------------------------------------------------------------------
final class zxd_read_result extends ffi.Struct {
  /// Raw content bytes. Allocated with the Dart-compatible allocator; owned
  /// by the caller after return. NULL iff bytes_len == 0.
  external ffi.Pointer<ffi.Uint8> bytes;

  @ffi.Uint32()
  external int bytes_len;

  /// Content rendered as NUL-terminated UTF-8 text. Same ownership as
  /// `bytes`. May be NULL.
  external ffi.Pointer<ffi.Char> text;

  /// Stable ZXD_FORMAT_* value of the decoded symbol (not an upstream enum).
  @ffi.Int32()
  external int format;

  /// Detection geometry in source-image pixel coordinates:
  /// [TLx, TLy, TRx, TRy, BRx, BRy, BLx, BLy].
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Int32> corners;
}

/// ---------------------------------------------------------------------------
/// zxd_encode_aztec: payload in, module matrix out.
///
/// Deliberately returns the symbol's bit matrix rather than pixels: rendering
/// is the embedder's job (CustomPainter draws the modules; the visual layer
/// around them is presentation, not codec).
/// ---------------------------------------------------------------------------
final class zxd_matrix extends ffi.Struct {
  /// Bit-packed modules, row-major, MSB-first within each byte, rows padded
  /// to whole bytes: row_stride_bytes = (width + 7) / 8. Bit set = dark
  /// module. Allocated with the Dart-compatible allocator; owned by the
  /// caller after return.
  external ffi.Pointer<ffi.Uint8> bits;

  /// modules per row
  @ffi.Uint32()
  external int width;

  /// rows
  @ffi.Uint32()
  external int height;
}

const int ZXD_ABI_VERSION = 2;

const int ZXD_OK = 0;

const int ZXD_NOT_FOUND = 1;

const int ZXD_INVALID_ARGUMENT = 2;

const int ZXD_ENCODE_ERROR = 3;

const int ZXD_INTERNAL_ERROR = 4;

const int ZXD_PIXEL_LUM8 = 0;

const int ZXD_PIXEL_RGBA8888 = 1;

const int ZXD_PIXEL_BGRA8888 = 2;

const int ZXD_FORMAT_ANY = 0;

const int ZXD_FORMAT_AZTEC = 1;

const int ZXD_FORMAT_QR_CODE = 2;
